In [2]:
import numpy as np

print("Version of you Numpy is:",np.__version__)

Version of you Numpy is: 2.3.4


In [4]:
#S1

num_list=[i for i in range(1,21)]
arr=np.array(num_list)
print("Arry with numbers (1-20)",arr)

Arry with numbers (1-20) [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [7]:
#S2
arr=np.zeros((3,3))

zero_matrix=np.matrix(arr)
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr=np.ones((5,5))
idn_matrix=np.matrix(arr)
print(idn_matrix)

In [12]:
#S4

import random


rand=np.random.default_rng()

arr=rand.integers(low=1,high=100,size=10)
print("10 Numbers from(1-100) are",arr)

10 Numbers from(1-100) are [63 61 33 58 27 64 43 48 60 89]


In [13]:
#S5

print("Maximum of the arr:",arr.max())
print("Minimum of the arr:",arr.min())
print("Average of the arr:",arr.mean())

Maximum of the arr: 89
Minimum of the arr: 27
Average of the arr: 54.6


In [22]:
arr=np.array((1,2,3,4,5,6,7,8,9,10,11,12))

arr.resize((3,4))
print(arr)

print("Resized Matrix:",np.matrix(arr))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Resized Matrix: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#S7
evern_arr=np.arange(2,102,2)
print(evern_arr)
print(len(evern_arr))

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
50


In [32]:
#S8

arr=rand.integers(low=1,high=100,size=100)

arr_greater_fifty=arr[arr>50]
print(arr_greater_fifty)

[79 65 95 99 90 93 59 97 97 64 54 61 87 80 68 98 83 53 66 82 63 60 74 94
 54 86 91 60 97 90 56 76 64 56 53 83 63 68 80 74]


In [ ]:
#S9
print("Orginal Arra:",arr)
reverse_arr=arr[::-1]
print("Reversed arr",reverse_arr)

Orginal Arra: [79 15  5 65 95  9 24 50 99 90 50 93 59 16 45 14 23 97 26 19 97 64 25 38
 45 45 34 54 61 20 15 87  2  3 46 45 25 36 21 27 40 21 80 68 98 83 33 13
 53 21 38 42 22  2 66 82 40 39  2 26 63  3 60 74 48 94 54 86 91  1 21  7
 60 21 97 38 90 56 33 40 76 21 31 64 26  5 35  9 56 53 83 27 41 63 11 68
 80 25 74  5]
Reversed arr [ 5 74 25 80 68 11 63 41 27 83 53 56  9 35  5 26 64 31 21 76 40 33 56 90
 38 97 21 60  7 21  1 91 86 54 94 48 74 60  3 63 26  2 39 40 82 66  2 22
 42 38 21 53 13 33 83 98 68 80 21 40 27 21 36 25 45 46  3  2 87 15 20 61
 54 34 45 45 38 25 64 97 19 26 97 23 14 45 16 59 93 50 90 99 50 24  9 95
 65  5 15 79]


In [40]:
#S10

float_arr=rand.uniform(low=0,high=1,size=100).round(3)
# float_arr=(float_arr[float_arr].round(3))
print("Array with float number",float_arr)

Array with float number [0.664 0.515 0.485 0.775 0.085 0.793 0.455 0.533 0.885 0.347 0.068 0.564
 0.461 0.866 0.297 0.07  0.699 0.122 0.465 0.024 0.397 0.686 0.977 0.132
 0.132 0.162 0.589 0.449 0.6   0.148 0.98  0.557 0.229 0.939 0.653 0.43
 0.095 0.549 0.567 0.281 0.815 0.024 0.747 0.028 0.309 0.625 0.044 0.754
 0.829 0.955 0.378 0.675 0.331 0.506 0.59  0.669 0.606 0.073 0.864 0.589
 0.2   0.233 0.561 0.761 0.609 0.997 0.672 0.568 0.533 0.315 0.414 0.673
 0.027 0.024 0.035 0.407 0.3   0.864 0.885 0.385 0.486 0.61  0.197 0.282
 0.536 0.513 0.214 0.451 0.974 0.261 0.246 0.782 0.44  0.958 0.234 0.796
 0.219 0.142 0.283 0.624]


In [ ]:
#IM Task-1
arr=np.ones((5,5))
print("Initial array:\n",arr)

arr[1:-1,1:-1]=0
print("Final array:\n",arr)

Initial array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Final array:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [52]:
arr=rand.integers(1,10,10)
print(arr)
arr=(arr- arr.min()) / (arr.max()- arr.min())
print(arr)

[7 8 5 8 9 5 5 8 6 1]
[0.75  0.875 0.5   0.875 1.    0.5   0.5   0.875 0.625 0.   ]


In [60]:
#IM Task-3

arr=rand.integers(1,10,10)
print("First array:\n",arr)

arr2=rand.integers(10,20,10)
print("Second array:\n",arr2)

arr3=rand.integers(30,40,10)
print(arr3)
print()

final_arr=np.vstack((arr,arr2,arr3))
print(final_arr)

final_arr=np.hstack((arr,arr2,arr3))
print(final_arr)

First array:
 [7 4 9 5 6 9 5 4 2 6]
Second array:
 [11 19 16 18 12 13 11 17 17 15]
[30 31 35 34 34 31 32 37 35 37]

[[ 7  4  9  5  6  9  5  4  2  6]
 [11 19 16 18 12 13 11 17 17 15]
 [30 31 35 34 34 31 32 37 35 37]]
[ 7  4  9  5  6  9  5  4  2  6 11 19 16 18 12 13 11 17 17 15 30 31 35 34
 34 31 32 37 35 37]


In [1]:
#IM task 4

arr=rand.integers(10,100,size=(10,10))
# arr.resize((10,10))
# arr=np.array(arr)
print(arr)
print("Row wise sum:",arr.sum(axis=1))
print("Column wise sum:",arr.sum(axis=0))

NameError: name 'rand' is not defined

In [72]:
arr = rand.integers(-10, 10, size=(3, 3))
print("Original:\n", arr)

arr[arr < 0] = 0
print("Modified:\n", arr)

arr = rand.integers(-10, 10, size=(3,3))
print("Original:\n", arr)

arr = np.where(arr < 0, 0, arr)
print("Modified:\n", arr)


Original:
 [[ -9 -10   9]
 [  9   6   6]
 [ -7  -8   0]]
Modified:
 [[0 0 9]
 [9 6 6]
 [0 0 0]]
Original:
 [[ 7  5 -9]
 [-8  2 -5]
 [ 3 -2  0]]
Modified:
 [[7 5 0]
 [0 2 0]
 [3 0 0]]


In [75]:
mat=np.matrix(arr)
dia_mat=np.diag(mat)
print(dia_mat)

[7 2 0]
